# Generated by Django 4.1 on 2022-09-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0002_alter_article_category_choice_alter_create_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('narrate', models.TextField(default='Enter Narration', max_length=9999)),
                ('review_narration', models.CharField(choices=[('PAS', 'Passed'), ('REV', 'For_Review'), ('ACC', 'Narration_Accepted')], default='Reviewing Narration', max_length=50)),
                ('translate', models.TextField(default='Enter Translation', max_length=9999)),
                ('review_translation', models.CharField(choices=[('PSD', 'Passed'), ('RVW', 'For_Review'), ('ACP', 'Translation_Accepted')], default='Reviewing Translation', max_length=50)),
                ('user', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='hobeapp.user')),
            ],
        ),
    ]
