# Generated by Django 4.1 on 2022-09-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0006_remove_profile_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
