# Generated by Django 4.1 on 2022-09-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0007_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hobeapp.user'),
            preserve_default=False,
        ),
    ]
